### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
"userId": 1,
"accountNumber": "1000000002",
"amount": 100
}

### calcel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
"transactionId": "4b1fb9c27a3946c4bfea9cc75bb0640b",
"accountNumber": "1000000002",
"amount": 20000
}
### query transaction
GET http://localhost:8080/transaction/3a1a55c701e14658b0f6537e3060ef66